# Generated by Django 3.1.6 on 2021-02-23 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InterpreterModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interpreter_name', models.CharField(max_length=100)),
                ('interpreter_image', models.ImageField(upload_to='artistimages')),
            ],
            options={
                'verbose_name': 'Interpreter',
                'verbose_name_plural': 'Interpreters',
            },
        ),
        migrations.CreateModel(
            name='LinksSongsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_title', models.CharField(max_length=100, null=True)),
                ('embed_youtube_link', models.URLField(blank=True, null=True)),
                ('embed_spotify_link', models.URLField(blank=True, null=True)),
                ('interpreters', models.ManyToManyField(to='songoftheday.InterpreterModel')),
            ],
            options={
                'verbose_name': 'Link',
                'verbose_name_plural': 'Links',
            },
        ),
        migrations.CreateModel(
            name='SongModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_title', models.CharField(max_length=100)),
                ('date_song', models.DateField()),
                ('composer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='songoftheday.interpretermodel')),
                ('interpreter', models.ManyToManyField(to='songoftheday.LinksSongsModel')),
            ],
            options={
                'verbose_name': 'Song',
                'verbose_name_plural': 'Songs',
            },
        ),
    ]
