# Generated by Django 3.1.6 on 2021-02-25 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songoftheday', '0002_auto_20210225_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songmodel',
            name='date_song',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
